### ISSUE TITLE
openvswitch-gbp 

### ISSUE THREAD

**Issue by irathore** [noironetworks/apic-ml2-driver#28]
Openvswitch kmod does not install for the right kernel version. It is installing for 3.10.0-229.14.1.el7.x86_64 which has been pulled for vulnerability. The default 7.1 kernel is 3.10.0-229.el7.x86_64 and yum update installs 3.10.0-229.14.1.el7.x86_64. The module does in work with any kernels and requires downloading 3.10.0-229.14.1.el7.x86_64 which is not easy to find and is insecure

**Comment by mandeepdhami** [comment]
As we no longer need cisco-compiled kernel module, I am closing this issue.
